willcapl/Life_Capture

app/models/playlist.rb
app/models/question.rb
app/models/response.rb
app/models/sub_user.rb
db/migrate/20231127155130_add_username_to_users.rb
db/migrate/20231127155957_create_sub_users.rb
db/migrate/20231127160301_create_questions.rb
db/migrate/20231127160422_create_responses.rb
db/migrate/20231127160543_create_playlists.rb
db/schema.rb
test/models/playlist_test.rb
test/models/question_test.rb
test/models/response_test.rb
test/models/sub_user_test.rb

added models to schema

---

app/models/playlist.rb
app/models/question.rb
app/models/sub_user.rb
app/models/user.rb

Validations added to models

---

Gemfile.lock
app/models/playlist.rb
app/models/question.rb
app/models/user.rb

## Description
- Validation fix
- Database created and migrated

validation fixed

---

config/routes.rb

- Added all routes that feature in spread sheet
 
/sub_user/new -> New
/sub_user/id/edit -> Edit
/sub_user/id -> Update
/sub_user/id -> Destroy
/sub_user -> Create
/sub_user/sub_user_id/questions -> Generate_questions?
/sub_user/id -> SHOW
/sub_user/sub_user_id/questions/question_id/responses
/sub_user/id
 
/dashboard

added all routes within spreadsheets

---

app/controllers/sub_users_controller.rb

sub-user controller created

---

app/views/devise/registrations/new.html.erb
config/initializers/devise.rb

- Added username to signup form
- Minor styling

signup form complete

---

app/models/playlist.rb
app/models/sub_user.rb
app/models/user.rb
app/views/sub_users/new.html.erb
app/views/sub_users/show.html.erb

sub user sign up form complete

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/_footer.html.erb
app/views/pages/dashboard.html.erb

Dashboard changes Footer changes

dashboard + footer

---

app/controllers/sub_users_controller.rb
app/models/sub_user.rb
app/views/layouts/application.html.erb
app/views/sub_users/edit.html.erb
app/views/sub_users/show.html.erb

- Added edit and destroy subuser functionality

added edit subuser, destroy subuser added to show page

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/sub_users/show.html.erb

- Added stlying to show page
- Added user flow buttons
-

styled show page and added userflow abilities

---

app/assets/stylesheets/pages/_dashboard.scss
app/controllers/questions_controller.rb
app/views/questions/index.html.erb
app/views/sub_users/show.html.erb
config/routes.rb

- Added questions index page, ready for video recording

video page added

---

Gemfile
Gemfile.lock
db/migrate/20231128155559_remove_title_from_questions.rb
db/schema.rb
db/seeds.rb

basic seed file complete

---

app/views/devise/sessions/new.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

- Added username to login page
- Edited seed file

added username to login and editted seed file

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_question_index.scss
app/controllers/questions_controller.rb
app/views/questions/index.html.erb
db/migrate/20231127160422_create_responses.rb
db/migrate/20231127163740_create_response_bookmarks.rb
db/migrate/20231128155559_remove_title_from_questions.rb
db/schema.rb
db/seeds.rb

- Edited schema
- Edited seed file

edited schema and seed file

---

app/controllers/questions_controller.rb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
config/routes.rb

- Added questions index page 
- Added question show page

added question index page and quesition show page

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_modal.scss
app/javascript/controllers/copy_controller.js
app/views/sub_users/show.html.erb

Clipboard words added modal needs css styling

Added model can copy url of website still needs css styling

---

app/assets/stylesheets/components/_modal.scss
app/views/sub_users/show.html.erb
db/schema.rb

added css to modal still needs more work

Added extra styling to the modal in sub_users/id page

---

app/assets/stylesheets/pages/_show.scss

added styling to the gerid

---

app/views/pages/dashboard.html.erb
app/views/sub_users/show.html.erb

Changed user selection routing on dashboard

Changed user selection routing on dashboard

---

app/assets/stylesheets/sub_users/_new.scss
app/javascript/controllers/question_button_controller.js
app/views/sub_users/new.html.erb
app/views/sub_users/other_new.html.erb
config/importmap.rb

- Added typed js feature to loading page

loading page text with typedjs

---

app/models/sub_user.rb
app/views/sub_users/show.html.erb

switched to gpt-4

---

app/assets/stylesheets/pages/_show.scss
app/controllers/playlists_controller.rb
app/controllers/sub_users_controller.rb
app/views/sub_users/show.html.erb
app/views/sub_users/stories.html.erb
config/routes.rb

# Description 
- Styled burger drop down 
- Added all stories and questions to navbar links

styled burger drop down

---

app/controllers/sub_users_controller.rb
app/views/sub_users/show.html.erb

- Sort by date and grouped dates

questions sort by dates page complete

---

.gitignore
app/controllers/sub_users_controller.rb
app/javascript/controllers/avatar_controller.js
app/javascript/controllers/question_button_controller.js
app/models/sub_user.rb
app/views/sub_users/new.html.erb
app/views/sub_users/other_new.html.erb
app/views/sub_users/show.html.erb
config/routes.rb
db/schema.rb

1. User can now add a image to their profile for themselves or someone else

Added image to profile feature

---

app/assets/stylesheets/pages/_show.scss
app/models/sub_user.rb

fixed some bugs
